import fs from "node:fs";
import path from "node:path";
import { normalizeAction } from "./AutomationActions.js";

/**
 * PlaywrightGenerator
 * Sinh project Playwright (spec, page object, test data, locator mapping, manifest)
 * từ một danh sách Approved Automation Mapping Artifact.
 * Generated code là dữ liệu dẫn xuất; không gọi AI, không bịa nghiệp vụ.
 */
export default class PlaywrightGenerator {
    /**
     * @param {object} options
     * @param {string} [options.outputDir] thư mục output (mặc định ./outputs/playwright)
     * @param {string} [options.baseUrl]
     */
    constructor({ outputDir = path.join(process.cwd(), "outputs", "playwright"), baseUrl = "" } = {}) {
        this.outputDir = outputDir;
        this.baseUrl = baseUrl || process.env.BASE_URL || "http://localhost:3000";
    }

    /**
     * Sinh project cho một module.
     * @param {Array<import('./AutomationMappingArtifact.js').default>} mappings  đã APPROVED
     * @param {object} options
     * @param {string} [options.module]
     * @param {string} [options.projectId]
     * @returns {{projectDir:string, files:string[], manifest:object}}
     */
    generate(mappings, { module = "Module", projectId = "" } = {}) {
        const moduleSlug = this.slugify(module || "module");
        const projectDir = path.join(this.outputDir, moduleSlug);
        const testsDir = path.join(projectDir, "tests");
        const pagesDir = path.join(projectDir, "pages");
        const dataDir = path.join(projectDir, "data");
        const locatorsDir = path.join(projectDir, "locators");

        fs.mkdirSync(testsDir, { recursive: true });
        fs.mkdirSync(pagesDir, { recursive: true });
        fs.mkdirSync(dataDir, { recursive: true });
        fs.mkdirSync(locatorsDir, { recursive: true });

        const files = [];
        const generatedFiles = [];

        // Nhóm page object theo pageObject
        const byPage = new Map();
        for (const m of mappings) {
            const page = m.pageObject || "page";
            if (!byPage.has(page)) byPage.set(page, []);
            byPage.get(page).push(m);
        }

        // Sinh page object
        for (const [pageName, pageMappings] of byPage) {
            const pageFile = path.join(pagesDir, `${pageName}.js`);
            const pageCode = this.buildPageObject(pageName, pageMappings);
            fs.writeFileSync(pageFile, pageCode);
            files.push(pageFile);
            generatedFiles.push(`pages/${pageName}.js`);
        }

        // Sinh test data + locator mapping
        const dataFile = path.join(dataDir, `${moduleSlug}.json`);
        const locatorsFile = path.join(locatorsDir, `${moduleSlug}.json`);
        const allLocators = new Map();
        const allData = {};
        for (const m of mappings) {
            for (const ref of m.locatorReferences || []) {
                if (ref && !allLocators.has(ref.locatorKey)) {
                    allLocators.set(ref.locatorKey, { strategy: ref.strategy, value: ref.value });
                }
            }
            Object.assign(allData, m.dataReferences || {});
        }
        fs.writeFileSync(dataFile, JSON.stringify(allData, null, 2));
        fs.writeFileSync(locatorsFile, JSON.stringify(Object.fromEntries(allLocators), null, 2));
        files.push(dataFile, locatorsFile);
        generatedFiles.push(`data/${moduleSlug}.json`, `locators/${moduleSlug}.json`);

        // Sinh spec cho từng mapping
        for (const m of mappings) {
            const specName = this.specFileName(m);
            const specFile = path.join(testsDir, specName);
            const specCode = this.buildSpec(m, pageNameOf(m));
            fs.writeFileSync(specFile, specCode);
            files.push(specFile);
            generatedFiles.push(`tests/${specName}`);
        }

        // Sinh config
        const configFile = path.join(projectDir, "playwright.config.js");
        fs.writeFileSync(configFile, this.buildConfig());
        files.push(configFile);
        generatedFiles.push("playwright.config.js");

        const manifest = {
            projectId: projectId || `PW-${moduleSlug}-${Date.now()}`,
            module,
            baseUrl: this.baseUrl,
            sourceArtifactIds: mappings.map((m) => m.artifactId),
            testCaseIds: mappings.map((m) => m.testCaseId),
            generatedAt: new Date().toISOString(),
            files: generatedFiles
        };
        fs.writeFileSync(path.join(projectDir, "manifest.json"), JSON.stringify(manifest, null, 2));
        files.push(path.join(projectDir, "manifest.json"));
        generatedFiles.push("manifest.json");

        return { projectDir, files, manifest };
    }

    pageObjectFor(m) {
        return m.pageObject || "page";
    }

    buildConfig() {
        return `// Generated by QA Copilot V2 — Playwright config (derived data, re-generable)
import { defineConfig } from "@playwright/test";

export default defineConfig({
    testDir: "./tests",
    timeout: 30000,
    fullyParallel: false,
    reporter: [["list"], ["json", { outputFile: "test-results.json" }]],
    use: {
        baseURL: process.env.BASE_URL || ${JSON.stringify(this.baseUrl)},
        headless: true,
        screenshot: "only-on-failure",
        trace: "retain-on-failure"
    }
});
`;
    }

    buildPageObject(pageName, pageMappings) {
        const locators = [];
        const seen = new Set();
        for (const m of pageMappings) {
            for (const ref of m.locatorReferences || []) {
                if (ref && !seen.has(ref.locatorKey)) {
                    seen.add(ref.locatorKey);
                    locators.push(ref);
                }
            }
        }
        const fields = locators
            .map((l) => `    this.${l.locatorKey} = ${this.locatorCall(l)};`)
            .join("\n");
        return `// Generated page object for "${pageName}" — derived data, re-generable
export class ${this.camel(pageName)}Page {
    constructor(page) {
        this.page = page;
${fields}
    }

    async goto(route = "/") {
        await this.page.goto(route);
    }
}
`;
    }

    locatorCall(ref) {
        const strategy = ref.strategy || "getByLabel";
        const value = ref.value;
        switch (strategy) {
            case "getByTestId":
                return `this.page.getByTestId(${JSON.stringify(value)})`;
            case "getByRole":
                return `this.page.getByRole(${this.roleArgs(value)})`;
            case "getByPlaceholder":
                return `this.page.getByPlaceholder(${JSON.stringify(value)})`;
            case "getByText":
                return `this.page.getByText(${JSON.stringify(value)})`;
            case "css":
                return `this.page.locator(${JSON.stringify(value)})`;
            case "getByLabel":
            default:
                return `this.page.getByLabel(${JSON.stringify(value)})`;
        }
    }

    roleArgs(value) {
        // value như: 'button, name: "Lưu"'
        const m = /^(button|link|textbox|checkbox|heading|dialog), name: (.+)$/.exec(value ?? "");
        if (m) return `{ role: ${JSON.stringify(m[1])}, name: ${m[2]} }`;
        return `{ role: ${JSON.stringify(value)} }`;
    }

    buildSpec(m, pageName) {
        const pageClass = `${this.camel(pageName)}Page`;
        const testName = this.safeTitle(m.feature || m.testCaseId);
        const actions = (m.actions || []).map((a) => this.actionLine(a, pageName, m.route));
        const assertions = (m.assertions || []).map((a) => this.assertionLine(a, pageName));
        const setup = (m.setup || []).map((s) => `    // setup: ${s.description}`);

        return `// Generated by QA Copilot V2 — TestCase ${m.testCaseId}
// Derived data. Traceability: mapping ${m.artifactId}
import { test, expect } from "@playwright/test";
import { ${pageClass} } from "../pages/${pageName}.js";

test.describe("${m.testCaseId} — ${this.escapeString(m.feature || m.title || "")}", () => {
    test(${JSON.stringify(testName)}, async ({ page }) => {
        const po = new ${pageClass}(page);
${setup.length ? "\n" + setup.join("\n") : ""}
${actions.join("\n")}
${assertions.join("\n")}
    });
});
`;
    }

    actionLine(action, pageName, route) {
        const po = `po`;
        const locatorRef = action.locatorKey ? `${po}.${action.locatorKey}` : null;
        switch (action.action) {
            case "open":
            case "goto": {
                const target = action.target || "";
                const useRoute =
                    route && !target.startsWith("/") && !/^https?:/i.test(target)
                        ? route
                        : target || route || "/";
                return `    await ${po}.goto(${JSON.stringify(useRoute)});`;
            }
            case "fill": {
                const val = this.valueExpr(action.valueRef);
                return `    await ${locatorRef}.fill(${val});`;
            }
            case "click":
                return `    await ${locatorRef}.click();`;
            case "select":
                return `    await ${locatorRef}.selectOption(${this.valueExpr(action.valueRef)});`;
            case "press":
                return `    await ${locatorRef}.press(${JSON.stringify(action.target || "Enter")});`;
            case "check":
                return `    await ${locatorRef}.check();`;
            case "wait":
                return `    await ${po}.page.waitForTimeout(500);`;
            case "screenshot":
                return `    await ${po}.page.screenshot();`;
            default:
                return `    // action not mapped: ${action.action}`;
        }
    }

    assertionLine(assertion, pageName) {
        const po = `po`;
        const locatorRef = assertion.locatorKey ? `${po}.${assertion.locatorKey}` : `${po}.page`;
        const expected = JSON.stringify(assertion.expectedValue ?? "");
        switch (assertion.type) {
            case "toBeHidden":
                return `    await expect(${locatorRef}).toBeHidden();`;
            case "toHaveValue":
                return `    await expect(${locatorRef}).toHaveValue(${expected});`;
            case "toContainText":
                return `    await expect(${locatorRef}).toContainText(${expected});`;
            case "toHaveText":
                return `    await expect(${locatorRef}).toHaveText(${expected});`;
            case "toBeEnabled":
                return `    await expect(${locatorRef}).toBeEnabled();`;
            case "toBeDisabled":
                return `    await expect(${locatorRef}).toBeDisabled();`;
            case "toHaveURL":
                return `    await expect(${po}.page).toHaveURL(${expected});`;
            case "toBeChecked":
                return `    await expect(${locatorRef}).toBeChecked();`;
            case "toBeVisible":
            default:
                return `    await expect(${locatorRef}).toBeVisible();`;
        }
    }

    valueExpr(valueRef) {
        if (!valueRef) return '""';
        if (typeof valueRef === "string" && valueRef.startsWith("literal:")) {
            return JSON.stringify(valueRef.slice("literal:".length));
        }
        return JSON.stringify(valueRef);
    }

    specFileName(m) {
        return `${this.slugify(m.testCaseId || m.artifactId)}.spec.js`;
    }

    safeTitle(text) {
        const t = String(text ?? "test").trim().replace(/\s+/g, " ");
        return t.slice(0, 120) || "test";
    }

    escapeString(text) {
        return String(text ?? "").replace(/[\\"]/g, (c) => `\\${c}`);
    }

    camel(text) {
        return String(text ?? "")
            .split(/[^a-z0-9]+/i)
            .map((p, i) =>
                p ? p[0].toUpperCase() + p.slice(1) : ""
            )
            .join("");
    }

    slugify(text) {
        return String(text ?? "")
            .trim()
            .toLowerCase()
            .normalize("NFD")
            .replace(/[\u0300-\u036f]/g, "")
            .replace(/đ/g, "d")
            .replace(/[^a-z0-9]+/g, "_")
            .replace(/^_+|_+$/g, "")
            .slice(0, 80);
    }
}

function pageNameOf(m) {
    return m.pageObject || "page";
}
