const ApplicationActions = Object.freeze({
    ANSWER_CLARIFICATION: "ANSWER_CLARIFICATION",

    REVIEW_REQUIREMENT: "REVIEW_REQUIREMENT",

    REVIEW_MODULE: "REVIEW_MODULE",

    REVIEW_SCENARIO: "REVIEW_SCENARIO",

    REVIEW_TEST_CASE: "REVIEW_TEST_CASE",

    CLARIFICATION_ANSWERED: "CLARIFICATION_ANSWERED",

    STAGE_APPROVED: "STAGE_APPROVED",

    NONE: "NONE",

    CHECK_ERROR: "CHECK_ERROR"
});

export default ApplicationActions;
