const ArtifactType = Object.freeze({
    REQUIREMENT: "REQUIREMENT",
    REQUIREMENT_ANALYSIS: "REQUIREMENT_ANALYSIS",
    MODULE_FEATURE: "MODULE_FEATURE",
    SCENARIO: "SCENARIO",
    TESTCASE: "TESTCASE",
    AUTOMATION_MAPPING: "AUTOMATION_MAPPING",
    PLAYWRIGHT_PROJECT: "PLAYWRIGHT_PROJECT",
    EXECUTION_RESULT: "EXECUTION_RESULT"
});

export default ArtifactType;
