const PipelineStatuses = Object.freeze({
    AWAITING_AI_CLARIFICATION: "AWAITING_AI_CLARIFICATION",

    AWAITING_REQUIREMENT_REVIEW: "AWAITING_REQUIREMENT_REVIEW",

    AWAITING_MODULE_REVIEW: "AWAITING_MODULE_REVIEW",

    AWAITING_SCENARIO_REVIEW: "AWAITING_SCENARIO_REVIEW",

    AWAITING_TEST_CASE_REVIEW: "AWAITING_TEST_CASE_REVIEW",

    COMPLETED: "COMPLETED",

    FAILED: "FAILED"
});

export default PipelineStatuses;
